### ISSUE TITLE
Problem parsing log files ..

### ISSUE THREAD

**Issue by raszuk** [amulog/amulog#2] opened 2024-05-28 21:22 UTC
Hi, 

I am facing the following issue: 

When parsing with directly using log2seq it works perfectly fine - no errors: 

python -m log2seq -i -p parser.py log_out.txt

but when parsing by amulog calling log2seq it generate errors in multiple lines when second parsed element is separated by "**"  literally when it begines like this: 

[R1][2024/02/16 19:47:46.008715]\*\*ERR\*\*[CONTAINER] container_restar......

CLI: python -m amulog db-make -c test.conf

My parser is identical in both cases: 

#!/usr/bin/env python

from log2seq import LogParser
from log2seq import preset
from log2seq.header import *
from log2seq.statement import *

header_rule3 = [
    Hostname('host'),
    ItemGroup(
        [
            Digit('year'),
            Digit('month'),
            Digit('day'),
            Time()
        ],
        separator='/ '
    ),
    String('level'),
    #UserItem('level', r"[a-zA-Z0-9.]+"),
    String('process_name', symbols='_'),
    Statement()
]

header_parser3 = HeaderParser(
    header_rule3, full_format=r'\[<0>\]\[<1>\]\-\-<2>\-\-\[<3>\]<4>'
)

header_parser4 = HeaderParser(
    header_rule3, full_format=r'\[<0>\]\[<1>\]\*\*<2>\*\*\[<3>\]<4>'
)

header_parser5 = HeaderParser(
    header_rule3, full_format=r'\[<0>\]\[<1>\]\[<2>\]\[<3>\]<4>'
)

statement_parser = preset.default_statement_parser()
parser = LogParser([header_parser3, header_parser4, header_parser5], statement_parser)

Any hint on how to debug this would be helpful.

**Comment by cpflat** [comment] 2024-05-29 06:37
I could not reproduce the error by simply inserting "**" in several forms to some sample logs.
The following information is needed for further troubleshooting.

* The versions of amulog and log2seq.
* The whole error message (You can mask some sensitive information manually if needed). I need to determine the place to emit the error in the source code.
* The completed parser script. In my environment, the given parser script seems incompleted and emits an error message "unbalanced parenthesis at position 52", which means the parser decription is inconsistent or broken, even on log2seq commands.
* A completed sample log message. You can replace parameters into something others. One line is enough.

**Comment by raszuk** [comment] 2024-05-29 08:36
Hi,

Many thx for your reply. I am happy to provide you with all information if you give me hints how to collect them. 

Neither of them shows version when executing help (perhaps this could be added too): 

(amulog) robert@nuc3-eo:~/amulog/test5$ python -m amulog -h
usage: __main__.py SUBCOMMAND [options and arguments] ...

subcommands:
  conf-defaults: Show default configurations.
  conf-diff: Show differences of 2 configuration files.
  conf-group-edit: Edit configuration files in a config group.
  conf-minimum: Remove default options and comments.
  conf-shadow: Copy configuration files.
  data-from-data: Re-arrange log file, splitting messages by date.
  data-from-db: Generate log data from DB.
  data-parse: Check log data parsing with log2seq.
  db-add: Add log data to existing database.
  db-anonymize: Anonymize templates and hostnames.
  db-anonymize-mapping: Generate anonymization mapping json.
  db-make: Initialize database and add log data.
  db-remake-group: Remake log template groups
  db-repair: Repair db schema after version updates.
  db-tag: Make log template tags.
  dump-lt: same as show-lt-import
  show-db-info: Show abstruction of database status.
  show-host: Show all hostnames in database.
  show-log: Search and show log messages.
  show-lt: Show all log templates in database.
  show-lt-import: Output log template definitions in importable format.
  show-ltg: Show all log template groups and their members.
  show-tag: Show all tags and their templates.
  show-tag-stats: Show all tags and their templates.

try "__main__.py SUBCOMMAND -h" to refer detailed subcommand usage
see also sub-libraries amulog.edit amulog.eval


(amulog) robert@nuc3-eo:~/amulog/test5$ python -m log2seq --help
Usage: python -m log2seq [OPTIONS] [FILES]...

  Parse log messages given in FILES (or stdin if FILES not given).

Options:
  -p, --parser TEXT   filename of parser script
  --encoding TEXT     encoding to load input data
  -o, --output TEXT   output filename
  -t, --type TEXT     output format type, one of [object, words]
  -i, --show-input    additionally show the input string line as is
  --skip-success      only show failed messages
  -s, --as-statement  consider input as statement (without header)
  -v, --verbose       verbose output to stderr
  --help              Show this message and exit.

I do not see any error ... basically only lines are skipped and I see them in fail.log 

Parser script and sample log attached.

I just installed both few days ago directly from the github, but it seems that amulog is really not calling log2seq as external program but tries to parse the content by itself. 

[parser.py.txt](https://github.com/amulog/amulog/files/15481381/parser.py.txt)

[sample_log.txt.txt](https://github.com/amulog/amulog/files/15481383/sample_log.txt.txt)

**Comment by cpflat** [comment] 2024-05-29 10:45
Thank you for your information, now I understand what is happening.
It is actually a bug in the cooperation between amulog and log2seq: amulog internally escapes some symbols in log strings (e.g., '*' and '@'), but log2seq does not take this into account when parsing the header.
This problem has not been expressed or reported because these symbols have never been included in the header before.
The fundamental solution requires a rethink of the design and may take so long.

The easiest way to avoid the bug is to add escape sequences to the corresponding full_format.

    full_format=r'\[<0>\]\[<1>\]\\\*\\\*<2>\\\*\\\*\[<3>\]<4>'

This worked in my amulog environment (although the log2seq test will not work instead).
I hope this workaround is helpful to you.


FYI:
You can check library versions on your Python package managers (e.g., pip).
If not, you can also check the versions on python interpreter:

    >>> import amulog
    >>> help(amulog)

**Comment by cpflat** [comment] 2024-06-07 01:10
I am closing this issue as @raszuk reported to me individually that it worked successfully.

**Closed by cpflat** 2024-06-07 01:09 UTC
